apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disk-writer-pv.yaml
  - pv-kustomize-config.yaml

replacements:
  # Replacements for PersistentVolume (pv.yaml)
  - source:
      kind: ConfigMap
      name: pv-kustomize-config
      fieldPath: data.disk-writer-pd-volume-handle
    targets:
      - select:
          kind: PersistentVolume
          name: disk-writer-pv
        fieldPaths:
        - spec.csi.volumeHandle

  - source:
      kind: ConfigMap
      name: pv-kustomize-config
      fieldPath: data.namespace
    targets:
      - select:
          kind: PersistentVolume
          name: disk-writer-pv
        fieldPaths:
        - spec.claimRef.namespace
