apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - disk-writer-pv.yaml
  - pv-kustomize-config.yaml

replacements:
  # Replacement for Namespace (namespace.yaml)
  - source:
      kind: ConfigMap
      name: pv-kustomize-config
      fieldPath: data.namespace # Source for the Namespace name
    targets:
      - select:
          kind: Namespace
        fieldPaths:
        - metadata.name # Specify fieldPath for clarity and robustness

  # Replacements for PersistentVolume (pv.yaml)
  - source:
      kind: ConfigMap
      name: pv-kustomize-config
      fieldPath: data.disk-writer-pd-volume-handle
    targets:
      - select:
          kind: PersistentVolume
          name: disk-writer-pv
        fieldPaths:
        - spec.csi.volumeHandle
