# This file is intended to be "sourced" from your shell.
# Please don't execute directly
SOURCE_CLUSTER_BAK=$SOURCE_CLUSTER
SOURCE_PD_NAME_BAK=$SOURCE_PD_NAME
SOURCE_PD_REPLICA_ZONES_BAK=$SOURCE_PD_REPLICA_ZONES
REGION_BAK=$REGION

export SOURCE_CLUSTER=$TARGET_CLUSTER
export SOURCE_PD_NAME=$TARGET_PD_NAME
export SOURCE_PD_REPLICA_ZONES=$TARGET_PD_REPLICA_ZONES
export REGION=$DR_REGION

export TARGET_CLUSTER=$SOURCE_CLUSTER_BAK
export TARGET_PD_NAME=$SOURCE_PD_NAME_BAK
export TARGET_PD_REPLICA_ZONES=$SOURCE_PD_REPLICA_ZONES_BAK
export DR_REGION=$REGION_BAK
