FROM google/cloud-sdk:latest
RUN apt-get update && \
    apt-get install -y jq && \
    apt-get install -y gettext && \
    rm -rf /var/lib/apt/lists/*
COPY failover.sh /
RUN mkdir -p pv-base
COPY pv-base /pv-base
CMD ["/failover.sh"]
