FROM google/cloud-sdk:latest
RUN apt-get update && \
    apt-get install -y jq && \
    apt-get install -y gettext && \
    rm -rf /var/lib/apt/lists/*
COPY failover.sh /
COPY failover-create-failback-pds.sh /
RUN mkdir -p kustomize/pv-base
COPY pv-base /kustomize/pv-base
CMD ["/failover.sh"]
