apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-writer-stateful-set
  namespace: NAMESPACE # Placeholder for NAMESPACE
spec:
  serviceName: "disk-writer"
  selector:
    matchLabels:
      app: disk-writer
  template:
    metadata:
      labels:
        app: disk-writer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: disk-writer
        image: IMAGE_URL # Placeholder for the full image string
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MOUNT_LOCATION
          value: /var/run/data
        volumeMounts:
        - name: disk-writer-volume
          mountPath: /var/run/data
      volumes:
      - name: disk-writer-volume
        persistentVolumeClaim:
          claimName: disk-writer-pvc
