apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - disk-writer-stateful-set.yaml
  - disk-writer-service.yaml
  - disk-writer-service-ilb.yaml
  - kustomize-config.yaml

replacements:
  # Replacement for Namespace (namespace.yaml)
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.namespace # Source for the Namespace name
    targets:
      - select:
          kind: Namespace
        fieldPaths:
        - metadata.name # Specify fieldPath for clarity and robustness

  # Replacements for PersistentVolumeClaim (pvc.yaml)
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.namespace
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: disk-writer-pvc
        fieldPaths:
        - metadata.namespace

  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.pd-size
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: disk-writer-pvc
        fieldPaths:
        - spec.resources.requests.storage

  # Replacements for StatefulSet (disk-writer-stateful-set.yaml)
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.namespace # Source for NAMESPACE
    targets:
      - select:
          kind: StatefulSet
          name: disk-writer-stateful-set
        fieldPaths:
        - metadata.namespace # Target Deployment's namespace

  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.image-url # Corrected fieldPath for the image source
    targets:
      - select:
          kind: StatefulSet
          name: disk-writer-stateful-set
        fieldPaths:
        - spec.template.spec.containers.[name=disk-writer].image # Target Deployment's image field

  # Replacements for Service (disk-writer-service.yaml)
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.namespace # Source for NAMESPACE
    targets:
      - select:
          kind: Service
          name: disk-writer-service
        fieldPaths:
        - metadata.namespace # Target Deployment's namespace

  # Replacements for Service (disk-writer-service-ilb.yaml)
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.namespace # Source for NAMESPACE
    targets:
      - select:
          kind: Service
          name: disk-writer-service-ilb
        fieldPaths:
        - metadata.namespace # Target Deployment's namespace
