apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-writer-pv # Name of the PV object in Kubernetes
spec:
  # Capacity must match or be greater than the PVC's request
  capacity:
    storage: PD_SIZE # Placeholder for Kustomize
  accessModes:
    - ReadWriteOnce # Or ReadWriteOncePod if using GKE Autopilot
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: disk-writer-pvc
    namespace: NAMESPACE # Placeholder for NAMESPACE
  # GCE Persistent Disk specific configuration
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: PD_NAME # Placeholder for SOURCE_PD_NAME
    fsType: ext4
